services:
  db:
    image: postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    restart: on-failure
    container_name: starter-rust-db
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: on-failure
    container_name: studease-rust-redis